global:
  scrape_interval: 5s
scrape_configs:
  - job_name: dtqs-api
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics
  - job_name: dtqs-worker
    static_configs:
      - targets: ["worker:8001"]
    metrics_path: /metrics
